dist: trusty
sudo: false
group: beta
language: java
addons:
  apt:
    packages:
    - chromium-browser
    - sqlite3
  firefox: "49.0"
before_install:
  - dpkg-query -l xvfb chromium-browser sqlite3
install: true
script: mvn --settings travis-maven-settings.xml install -B -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET
