language: java
addons:
  apt:
    packages:
    - sqlite3
    - netpbm
    - firefox
    - google-chrome-stable
before_install:
  - dpkg-query -l xvfb chromium-browser sqlite3 firefox google-chrome-stable || true
notifications:
  email: false
install: true
script: mvn --settings travis-maven-settings.xml install -U -B -P travis -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET -Dselenium-help.chromedriver.version=$CHROMEDRIVER_VERSION
