language: java
addons:
  apt:
    packages:
    - chromium-browser
    - sqlite3
    - netpbm
  firefox: "latest"
before_install:
  - dpkg-query -l xvfb chromium-browser sqlite3 firefox
notifications:
  email: false
install: true
script: mvn --settings travis-maven-settings.xml install -B -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET -Dchrome.headless.tests.disabled=true
